log_dir: ./logs/logging/Brennandataset

state: INFO

cuda: 0

model_name: BrainECHO

num_epoch_finetune: [40, 40]

T_max: [40, 40]

lr_finetune: [1e-4, 1e-4]

batch_size: [16, 16]

checkpoint: checkpoints/whisper_decoding/Brennan_dataset/Brennan_dataset-mel-vqvae-pretrain-400400-2e-4/MelVQVAE_b16_400_0.0002_pretrain.pt

finetune_optimizer: adamw
task_name: eeg2text
