log_dir: ./logs/logging/Brennandataset_test

cuda: 0

model_name: MelVQUpsampleAlignWhisper

num_epoch_finetune: 40

lr_finetune: 1e-4
batch_size: 16
finetune_optimizer: adamw
task_name: eeg2text
state: INFO