log_dir: ./logs/logging/megdataset

state: INFO

dataset_path: ./datasets/meg/

cuda: 0

model_name: MelVQVAE

num_epoch_fintune: 100

T_max: 100

lr_finetune: 2e-4

batch_size: 16

save_path: ./checkpoints/whisper_decoding/meg_dataset/meg_dataset-mel-vqvae-pretrain-100100-2e-4
finetune_optimizer: adamw
task_name: meg2text
